CREATE DATABASE IF NOT EXISTS TRAIN_DB;
USE TRAIN_DB;

CREATE TABLE TRAINRECORD
	(
		T_ID 			char(5) primary key,
        T_DETIME 		varchar(20) not null,
        T_ARTIME 		varchar(20) not null,
        T_TICKETPRICE	int not null,
        T_SEAT			int not null,
        T_START			varchar(50) not null,
        T_DESTINATION	varchar(50) not null
	);	
    
CREATE TABLE STAFF
	(
		S_USERNAME 		varchar(20) not null,
        S_PASSWORD 		varchar(20) not null,
        CONSTRAINT PK_STAFF PRIMARY KEY (S_USERNAME,S_PASSWORD)
	);	
    
INSERT INTO `train_db`.`TRAINRECORD` (`T_ID`, `T_DETIME`, `T_ARTIME`, `T_TICKETPRICE`, `T_SEAT`, `T_START`, `T_DESTINATION`) VALUES ('00001', '13:30', '15:30', '15', '150', 'SALAYA', 'NAKHONPATHOM');
INSERT INTO `train_db`.`TRAINRECORD` (`T_ID`, `T_DETIME`, `T_ARTIME`, `T_TICKETPRICE`, `T_SEAT`, `T_START`, `T_DESTINATION`) VALUES ('00002', '12:00', '17:00', '60', '250', 'BANGKOK', 'HUAHIN');
INSERT INTO `train_db`.`TRAINRECORD` (`T_ID`, `T_DETIME`, `T_ARTIME`, `T_TICKETPRICE`, `T_SEAT`, `T_START`, `T_DESTINATION`) VALUES ('00003', '07:00', '12:00', '35', '200', 'BANGKOK', 'PATTAYA');
INSERT INTO `train_db`.`TRAINRECORD` (`T_ID`, `T_DETIME`, `T_ARTIME`, `T_TICKETPRICE`, `T_SEAT`, `T_START`, `T_DESTINATION`) VALUES ('0004', '09:00', '11:00', '25', '150', 'BANGKOK', 'SALAYA');
SELECT * FROM TRAINRECORD;


INSERT INTO `train_db`.`STAFF` (`S_USERNAME`, `S_PASSWORD`) VALUES ('STAFF', 'STAFF4321');
INSERT INTO `train_db`.`STAFF` (`S_USERNAME`, `S_PASSWORD`) VALUES ('STAFF', '1234');
SELECT * FROM STAFF;
SELECT * FROM STAFF WHERE S_USERNAME = 'STAFF' AND S_PASSWORD = 'STAFF4321';

